language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t dbandurin/docker-react -f Dockerfile.dev .

script:
  - docker run dbandurin/docker-react npm run test -- --coverage

